[package]
name = "my_public_crate_hh"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A add function where you sum two number."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
